# Generated by Django 6.0.3 on 2026-03-25 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_first_name', models.CharField(max_length=200)),
                ('client_middle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('client_last_name', models.CharField(max_length=200)),
                ('client_address', models.CharField(max_length=200)),
                ('client_contact_number', models.CharField(max_length=11)),
                ('client_civil_status', models.CharField(max_length=200)),
                ('client_date_birth', models.DateField()),
                ('client_religion', models.CharField(max_length=200)),
                ('client_occupation', models.CharField(max_length=200)),
                ('client_employer_name', models.CharField(max_length=200)),
                ('client_employer_address', models.CharField(max_length=200)),
                ('client_spouse_name', models.CharField(blank=True, max_length=200, null=True)),
                ('client_spouse_date_birth', models.DateField(blank=True, null=True)),
                ('client_spouse_occupation', models.CharField(blank=True, max_length=200, null=True)),
                ('client_spouse_employer', models.CharField(blank=True, max_length=200, null=True)),
                ('client_id_type', models.CharField(max_length=200)),
                ('client_id_number', models.CharField(max_length=20)),
                ('client_date_issued', models.DateField()),
                ('client_place_issued', models.CharField(max_length=200)),
                ('client_beneficiary_name', models.CharField(max_length=200)),
                ('client_beneficiary_relationship', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('time_in', models.DateTimeField(blank=True, null=True)),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('activities', models.CharField(max_length=500)),
                ('pin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=200)),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=20)),
                ('duration', models.IntegerField()),
                ('months_remaining', models.IntegerField()),
                ('start_date', models.DateField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('paid_balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.clientpersonalinfo')),
            ],
        ),
    ]
