# Generated by Django 6.0.3 on 2026-03-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientstatus',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
