# Generated by Django 6.0.3 on 2026-03-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_clientpersonalinfo_client_civil_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpersonalinfo',
            name='client_contact_number',
            field=models.CharField(max_length=13),
        ),
    ]
