# Generated by Django 6.0.3 on 2026-03-27 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_clientpersonalinfo_client_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientpersonalinfo',
            name='client_beneficiary_name',
        ),
        migrations.RemoveField(
            model_name='clientpersonalinfo',
            name='client_beneficiary_relationship',
        ),
    ]
