# Generated by Django 6.0.3 on 2026-03-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_clientpersonalinfo_client_beneficiary_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpersonalinfo',
            name='client_id_type',
            field=models.CharField(choices=[('Passport', 'Passport'), ("Driver's License", "Driver's License"), ('National ID', 'National ID'), ('SSS ID', 'SSS ID'), ('GSIS ID', 'GSIS ID'), ('UMID', 'UMID'), ('Postal ID', 'Postal ID')], max_length=50),
        ),
    ]
