# Generated by Django 6.0.3 on 2026-03-29 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_clientpersonalinfo_client_id_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
                ('client_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.clientstatus')),
            ],
            options={
                'ordering': ['month'],
            },
        ),
    ]
