# Generated by Django 6.0.3 on 2026-04-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_userlog_name_remove_userlog_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlog',
            name='employee_id',
        ),
        migrations.AlterField(
            model_name='userlog',
            name='role',
            field=models.CharField(blank=True, choices=[('Office Staff', 'Office Staff')], max_length=200, null=True),
        ),
    ]
