# Generated by Django 6.0.3 on 2026-05-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_userlog_employee_id_alter_userlog_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientstatus',
            name='down_payment',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='clientstatus',
            name='lot_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clientstatus',
            name='pa_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clientstatus',
            name='phase',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clientstatus',
            name='section',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientstatus',
            name='duration',
            field=models.IntegerField(choices=[(6, '6 Months'), (12, '12 Months'), (24, '24 Months'), (36, '36 Months'), (60, '60 Months')], max_length=20),
        ),
        migrations.AlterField(
            model_name='clientstatus',
            name='plan',
            field=models.CharField(choices=[('Lawn lot', 'Lawn lot'), ('Garden lot', 'Garden lot'), ('Junior court', 'Junior court'), ('Executive court', 'Executive court'), ('Senior court', 'Senior court'), ('Family estate', 'Family estate'), ('Grand estate', 'Grand estate')], max_length=200),
        ),
    ]
