# Generated by Django 6.0.3 on 2026-05-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_clientstatus_down_payment_clientstatus_lot_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientstatus',
            name='down_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientstatus',
            name='duration',
            field=models.IntegerField(choices=[(6, '6 Months'), (12, '12 Months'), (24, '24 Months'), (36, '36 Months'), (60, '60 Months')]),
        ),
    ]
