# Generated by Django 6.0.3 on 2026-05-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_clientstatus_block_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientstatus',
            name='plan',
            field=models.CharField(choices=[('No Plan', 'No Plan'), ('Lawn lot', 'Lawn lot'), ('Garden lot', 'Garden lot'), ('Junior court', 'Junior court'), ('Executive court', 'Executive court'), ('Senior court', 'Senior court'), ('Family estate', 'Family estate'), ('Grand estate', 'Grand estate')], max_length=200),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='pin',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('booking_date', 'booking_time')},
        ),
    ]
