# Generated by Django 6.0.3 on 2026-05-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_add_lot_types_columbarium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientstatus',
            name='column_level',
            field=models.CharField(blank=True, help_text='Column Level for THS/THTC lots.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientstatus',
            name='date_fully_paid',
            field=models.DateField(blank=True, help_text='Auto-filled when the last monthly payment is settled.', null=True),
        ),
        migrations.AlterField(
            model_name='clientstatus',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage discount on the down payment (0 = no discount).', max_digits=5),
        ),
    ]
