# Generated by Django 6.0.3 on 2026-06-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_clientstatus_column_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='role',
            field=models.CharField(blank=True, choices=[('General Staff', 'General Staff'), ('Financial Staff', 'Financial Staff')], max_length=200, null=True),
        ),
    ]
