# Generated by Django 5.2.17 on 2026-09-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_tct_ar_rename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientstatus',
            name='column_level',
            field=models.CharField(blank=True, help_text='Column/level value for THTC and TCT A/R lots.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='note',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
