# Generated by Django 6.1.1 on 2026-09-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_clientstatus_column_level_alter_payment_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientstatus',
            name='ths_section',
            field=models.CharField(blank=True, choices=[('St. Vincent', 'St. Vincent'), ('St. John', 'St. John'), ('St. Luke', 'St. Luke'), ('St. Mathew', 'St. Mathew'), ('St. Mark', 'St. Mark'), ('St. Paul - Love', 'St. Paul - Love'), ('St. Paul - Hope', 'St. Paul - Hope'), ('St. Paul - Faith', 'St. Paul - Faith'), ('St. Paul - Justice', 'St. Paul - Justice')], max_length=50, null=True),
        ),
    ]
